version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-auth
    environment:
      - POSTGRES_PASSWORD=databasepassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    container_name: redis-auth
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=yes
    ports:
      - '6379:6379'
